<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CCS.Domain\CCS.Domain.csproj" />
    <ProjectReference Include="..\CCS.Shared\CCS.Shared.csproj" />
  </ItemGroup>

</Project>
